version: '3.8'
services:
  postgres-test:
    image: postgres:15-alpine
    container_name: social-auth-postgres-test
    environment:
      POSTGRES_DB: social_auth_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # 개발용 DB와 포트 충돌 방지
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./sql/init-test.sql:/docker-entrypoint-initdb.d/init-test.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d social_auth_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
