server:
  port: 8082

spring:
  application:
    name: postgres-module
    
  # PostgreSQL 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/practice_db
    username: daniel
    password: password123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.daniel.practice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
