server:
  port: 8083

spring:
  application:
    name: redis-module
    
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# 캐시 설정
  cache:
    type: redis
    redis:
      time-to-live: 1800000  # 30분

logging:
  level:
    com.daniel.practice: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
